name: SBOM
on:
  release:
    types: [published]
  workflow_dispatch:
          
permissions: read-all

jobs:
  generate-sboms:
    runs-on: ubuntu-latest
    env:
      NPM_CONFIG_UNSAFE_PERM: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install -g npm@latest

      - name: Bootstrap
        run: npm install

      - name: Generate SBOM for the whole repository
        if: ${{ ! startsWith(github.ref, 'refs/tags/experimental') && ! startsWith(github.ref, 'refs/tags/api') }}
        run: |
          npm sbom --sbom-format=spdx --legacy-peer-deps > test1.spdx.json

      - name: Generate SBOM for API
        if: startsWith(github.ref, 'refs/tags/api/')
        run: |
          npm sbom --sbom-format=spdx --legacy-peer-deps > api.spdx.json

      - name: Generate SBOM for experimental
        if: startsWith(github.ref, 'refs/tags/experimental/')
        run: |
          npm sbom --sbom-format=spdx --legacy-peer-deps > experimental.spdx.json

      - name: Zip all SBOM files
        run: |
          zip sbom.zip *.spdx.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SBOM.zip
          path: ./sbom.zip

  add-release-artifact:
    needs: generate-sboms
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact from generate-sboms
        uses: actions/download-artifact@v4
        with:
          name: SBOM.zip
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./sbom.zip
          asset_name: SBOM.zip
          asset_content_type: application/zip
